wandb_version: 1

epochs:
  desc: null
  value: 250
batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 42
optimizer:
  desc: null
  value: AdamW
scheduler:
  desc: null
  value: ReduceOP
criterion:
  desc: null
  value: MSE
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715271925.343202
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.0
      6: 4.29.2
      8:
      - 3
      - 5
